[package]
name = "day_6"
version = "0.1.0"
authors = ["Nenad Petkovic <root@nenad-petkovic.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
array_tool = "1.0.3"
